#include "bms_afe_mock.h"
#include "bms_boot_image.h"
#include "bms_boot_metadata.h"
#include "bms_boot_policy.h"
#include "bms_crc32.h"
#include "bms_frame.h"
#include "bms_iap_session.h"
#include "bms_protection.h"
#include <stdio.h>
#include <string.h>
int bms_test_app_core(void);
#define CHECK(x) do { if (!(x)) { printf("FAIL:%s:%d:%s\n",__FILE__,__LINE__,#x); return 1; } } while(0)
typedef struct{uint32_t base;uint8_t bytes[512];bms_boot_meta_record_t meta_a,meta_b;uint8_t use_b;unsigned erase_count,write_count;}flash_model_t;
static int flash_read(void *ctx,uint32_t address,uint8_t *dst,size_t length){flash_model_t *f=(flash_model_t *)ctx;size_t o;if((f==NULL)||(dst==NULL)||(address<f->base))return -1;o=(size_t)(address-f->base);if((o>sizeof(f->bytes))||(length>(sizeof(f->bytes)-o)))return -1;(void)memcpy(dst,&f->bytes[o],length);return 0;}
static int flash_erase(void *ctx){flash_model_t *f=(flash_model_t *)ctx;if(f==NULL)return -1;(void)memset(f->bytes,0xFF,sizeof(f->bytes));f->erase_count++;return 0;}
static int flash_write(void *ctx,uint32_t address,const uint8_t *data,size_t length){flash_model_t *f=(flash_model_t *)ctx;size_t o,i;if((f==NULL)||(data==NULL)||(address<f->base))return -1;o=(size_t)(address-f->base);if((o>sizeof(f->bytes))||(length>(sizeof(f->bytes)-o)))return -1;for(i=0U;i<length;++i){if((f->bytes[o+i]&data[i])!=data[i])return -1;f->bytes[o+i]=data[i];}f->write_count++;return 0;}
static int metadata_store(void *ctx,bms_boot_meta_state_t state,const bms_image_manifest_t *image){flash_model_t *f=(flash_model_t *)ctx;const bms_boot_meta_record_t *current;bms_boot_meta_record_t *dst;if(f==NULL)return -1;current=bms_boot_metadata_select(&f->meta_a,&f->meta_b);dst=(f->use_b!=0U)?&f->meta_b:&f->meta_a;bms_boot_metadata_prepare_next(dst,current,state,image);f->use_b^=1U;return 0;}
static void put32(uint8_t *p,uint32_t v){p[0]=(uint8_t)v;p[1]=(uint8_t)(v>>8U);p[2]=(uint8_t)(v>>16U);p[3]=(uint8_t)(v>>24U);}
static int test_crc(void){static const uint8_t t[]="123456789";CHECK(bms_crc32(t,9U)==0xCBF43926UL);return 0;}
static int test_frame(void){uint8_t f[64];size_t n=0U;bms_frame_view_t v;const uint8_t p[]={1U,2U,3U};CHECK(bms_frame_encode(1U,7U,0x1234U,p,3U,f,sizeof(f),&n)==BMS_FRAME_OK);CHECK(bms_frame_decode(f,n,&v)==BMS_FRAME_OK);CHECK(v.sequence==7U);CHECK(v.command==0x1234U);f[10]^=1U;CHECK(bms_frame_decode(f,n,&v)==BMS_FRAME_ERR_CRC);return 0;}
static int test_image(void){flash_model_t f={0};bms_image_manifest_t m={0};bms_image_constraints_t c={0};f.base=0x08003000UL;put32(&f.bytes[0],0x20002000UL);put32(&f.bytes[4],0x08003101UL);f.bytes[8]=0xAAU;f.bytes[9]=0x55U;m.magic=BMS_IMAGE_MAGIC;m.manifest_version=BMS_IMAGE_MANIFEST_VERSION;m.mcu_id=BMS_MCU_STM32F030C8;m.product_id=42U;m.image_size=10U;m.image_crc32=bms_crc32(f.bytes,10U);c.app_start=f.base;c.app_end_exclusive=f.base+(uint32_t)sizeof(f.bytes);c.ram_start=0x20000000UL;c.ram_end_exclusive=0x20002000UL;c.mcu_id=BMS_MCU_STM32F030C8;c.product_id=42U;CHECK(bms_boot_image_validate(&m,&c,flash_read,&f)==BMS_IMAGE_OK);m.image_crc32^=1U;CHECK(bms_boot_image_validate(&m,&c,flash_read,&f)==BMS_IMAGE_ERR_CRC);return 0;}
static int test_metadata(void){bms_boot_meta_record_t a,b;bms_image_manifest_t image={0};image.magic=BMS_IMAGE_MAGIC;image.manifest_version=BMS_IMAGE_MANIFEST_VERSION;bms_boot_metadata_prepare_next(&a,NULL,BMS_BOOT_META_RECEIVING,&image);bms_boot_metadata_prepare_next(&b,&a,BMS_BOOT_META_READY,&image);CHECK(bms_boot_metadata_select(&a,&b)==&b);b.record_crc32^=1U;CHECK(bms_boot_metadata_select(&a,&b)==&a);return 0;}
static int test_policy(void){bms_boot_policy_input_t in={0};in.app_valid=1U;in.boot_failure_limit=3U;in.app_confirmed_healthy=1U;CHECK(bms_boot_policy_decide(&in)==BMS_BOOT_START_APP);in.upgrade_requested=1U;CHECK(bms_boot_policy_decide(&in)==BMS_BOOT_ENTER_RECOVERY);return 0;}
static int test_iap(void){flash_model_t f={0};bms_iap_storage_t s={flash_erase,flash_write,flash_read,metadata_store,&f};bms_iap_session_t session;bms_image_constraints_t c={0};bms_image_manifest_t image={0};uint8_t app[10];const bms_boot_meta_record_t *meta;f.base=0x08003000UL;(void)memset(f.bytes,0xFF,sizeof(f.bytes));put32(&app[0],0x20002000UL);put32(&app[4],0x08003101UL);app[8]=0xA5U;app[9]=0x5AU;c.app_start=f.base;c.app_end_exclusive=f.base+(uint32_t)sizeof(f.bytes);c.ram_start=0x20000000UL;c.ram_end_exclusive=0x20002000UL;c.mcu_id=BMS_MCU_STM32F030C8;c.product_id=42U;image.magic=BMS_IMAGE_MAGIC;image.manifest_version=BMS_IMAGE_MANIFEST_VERSION;image.mcu_id=c.mcu_id;image.product_id=c.product_id;image.image_size=(uint32_t)sizeof(app);image.image_crc32=bms_crc32(app,sizeof(app));bms_iap_session_init(&session,&c);CHECK(bms_iap_start(&session,&s,&image)==BMS_IAP_OK);CHECK(bms_iap_write_chunk(&session,&s,0U,&app[0],8U)==BMS_IAP_OK);CHECK(bms_iap_write_chunk(&session,&s,0U,&app[0],8U)==BMS_IAP_OK_DUPLICATE);CHECK(bms_iap_write_chunk(&session,&s,8U,&app[8],2U)==BMS_IAP_OK);CHECK(bms_iap_verify(&session,&s)==BMS_IAP_OK);CHECK(bms_iap_commit(&session,&s)==BMS_IAP_OK);meta=bms_boot_metadata_select(&f.meta_a,&f.meta_b);CHECK(meta!=NULL);CHECK(meta->state==(uint32_t)BMS_BOOT_META_READY);return 0;}
static int test_protection(void){bms_protection_t p;bms_protection_config_t c={3650,3600,1000U,500U,BMS_PROTECT_MODE_HIGH,1U};bms_protection_init(&p);CHECK(bms_protection_step(&p,&c,3649,500U)==BMS_PROTECT_NORMAL);CHECK(bms_protection_step(&p,&c,3650,500U)==BMS_PROTECT_PENDING);CHECK(bms_protection_step(&p,&c,3651,500U)==BMS_PROTECT_ACTIVE);CHECK(bms_protection_step(&p,&c,3600,500U)==BMS_PROTECT_NORMAL);return 0;}
static int test_afe(void){bms_afe_t a;bms_afe_mock_context_t c={0};bms_afe_sample_t o;bms_afe_mock_bind(&a,&c);CHECK(a.ops->init(&a)==0);c.sample.current_ma=1234;CHECK(a.ops->sample(&a,&o)==0);CHECK(o.current_ma==1234);return 0;}
int main(void){CHECK(test_crc()==0);CHECK(test_frame()==0);CHECK(test_image()==0);CHECK(test_metadata()==0);CHECK(test_policy()==0);CHECK(test_iap()==0);CHECK(test_protection()==0);CHECK(test_afe()==0);CHECK(bms_test_app_core()==0);printf("BMS_HOST_TESTS_PASS\n");return 0;}
