#ifndef BMS_COMMANDS_H
#define BMS_COMMANDS_H

#include <stdint.h>

typedef enum {
    BMS_MSG_REQUEST = 1,
    BMS_MSG_RESPONSE = 2,
    BMS_MSG_EVENT = 3
} bms_message_type_t;

typedef enum {
    BMS_CMD_DEVICE_INFO = 0x0001,
    BMS_CMD_PROTOCOL_INFO = 0x0002,
    BMS_CMD_CAPABILITIES = 0x0003,

    BMS_CMD_TELEMETRY_SNAPSHOT = 0x0101,
    BMS_CMD_TELEMETRY_CELLS = 0x0102,
    BMS_CMD_TELEMETRY_TEMPS = 0x0103,

    BMS_CMD_PROTECTION_SUMMARY = 0x0201,
    BMS_CMD_PROTECTION_DESCRIPTORS = 0x0202,
    BMS_CMD_PROTECTION_CLEAR_LATCH = 0x0203,

    BMS_CMD_PARAMETER_DESCRIPTORS = 0x0301,
    BMS_CMD_PARAMETER_READ = 0x0302,
    BMS_CMD_PARAMETER_WRITE = 0x0303,
    BMS_CMD_PARAMETER_COMMIT = 0x0304,
    BMS_CMD_PARAMETER_ABORT = 0x0305,

    BMS_CMD_CONTROL_POWER_PATH = 0x0401,
    BMS_CMD_CONTROL_ENTER_IAP = 0x0402,

    BMS_CMD_LOG_INFO = 0x0501,
    BMS_CMD_LOG_READ = 0x0502,
    BMS_CMD_LOG_CLEAR = 0x0503,

    BMS_CMD_DIAGNOSTIC_SNAPSHOT = 0x0601,
    BMS_CMD_DIAGNOSTIC_RESET_CAUSE = 0x0602,
    BMS_CMD_DIAGNOSTIC_COUNTERS = 0x0603,

    BMS_CMD_IAP_INFO = 0x1000,
    BMS_CMD_IAP_START = 0x1001,
    BMS_CMD_IAP_WRITE = 0x1002,
    BMS_CMD_IAP_VERIFY = 0x1003,
    BMS_CMD_IAP_COMMIT = 0x1004,
    BMS_CMD_IAP_ABORT = 0x1005,
    BMS_CMD_IAP_REBOOT = 0x1006,
    BMS_CMD_IAP_PROGRESS = 0x1007
} bms_command_id_t;

typedef enum {
    BMS_STATUS_OK = 0,
    BMS_STATUS_INVALID_ARGUMENT = 1,
    BMS_STATUS_INVALID_STATE = 2,
    BMS_STATUS_INVALID_IMAGE = 3,
    BMS_STATUS_RANGE = 4,
    BMS_STATUS_SEQUENCE = 5,
    BMS_STATUS_STORAGE = 6,
    BMS_STATUS_VERIFY = 7,
    BMS_STATUS_UNSUPPORTED = 8,
    BMS_STATUS_INTERNAL = 255
} bms_status_code_t;

#endif
