<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../../generated/parameters/ParameterIds.g.cs" Link="Generated/ParameterIds.g.cs" />
    <Compile Include="../../../generated/protections/ProtectionIds.g.cs" Link="Generated/ProtectionIds.g.cs" />
    <Compile Include="../../../generated/events/EventIds.g.cs" Link="Generated/EventIds.g.cs" />
  </ItemGroup>
</Project>
