#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema/commands.json"
OUTPUTS = {
    ROOT / "generated/commands/bms_command_ids.h": "c",
    ROOT / "generated/commands/CommandIds.g.cs": "cs",
    ROOT / "docs/generated/COMMAND_TABLE.md": "md",
}
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
SERVICE_RANGES = {
    "device": (0x0000, 0x00FF),
    "telemetry": (0x0100, 0x01FF),
    "protection": (0x0200, 0x02FF),
    "parameter": (0x0300, 0x03FF),
    "control": (0x0400, 0x04FF),
    "log": (0x0500, 0x05FF),
    "diagnostic": (0x0600, 0x06FF),
    "iap": (0x1000, 0x10FF),
}


def load_schema() -> dict:
    data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = data.get("schema_version")
    commands = data.get("commands")
    if not isinstance(version, int) or version <= 0 or version > 0xFFFF:
        raise SystemExit("command schema_version must be 1..65535")
    if not isinstance(commands, list):
        raise SystemExit("command schema commands must be a list")
    seen_ids: set[int] = set()
    seen_names: set[str] = set()
    for item in commands:
        if not isinstance(item, dict):
            raise SystemExit("command entry must be an object")
        ident = item.get("id")
        name = item.get("name")
        service = item.get("service")
        if not isinstance(ident, int) or ident <= 0 or ident > 0xFFFF:
            raise SystemExit(f"invalid command id: {ident!r}")
        if ident in seen_ids:
            raise SystemExit(f"duplicate command id: {ident}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            raise SystemExit(f"invalid command name: {name!r}")
        if name in seen_names:
            raise SystemExit(f"duplicate command name: {name}")
        if service not in SERVICE_RANGES:
            raise SystemExit(f"invalid command service for {name}: {service!r}")
        low, high = SERVICE_RANGES[service]
        if not low <= ident <= high:
            raise SystemExit(f"command {name} id 0x{ident:04X} is outside {service} range")
        seen_ids.add(ident)
        seen_names.add(name)
    data["commands"] = sorted(commands, key=lambda item: item["id"])
    return data


def render_c(data: dict) -> str:
    lines = [
        "/* Generated from schema/commands.json. Do not edit. */",
        "#ifndef BMS_COMMAND_IDS_H",
        "#define BMS_COMMAND_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define BMS_COMMAND_SCHEMA_VERSION UINT16_C({data['schema_version']})",
    ]
    for item in data["commands"]:
        lines.append(f"#define BMS_CMD_{item['name']} UINT16_C({item['id']})")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_cs(data: dict) -> str:
    lines = [
        "// Generated from schema/commands.json. Do not edit.",
        "namespace Bms.Protocol.Generated;",
        "",
        "public static class CommandIds",
        "{",
        f"    public const ushort SchemaVersion = {data['schema_version']};",
    ]
    for item in data["commands"]:
        name = "".join(part.title() for part in item["name"].lower().split("_"))
        lines.append(f"    public const ushort {name} = {item['id']};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_md(data: dict) -> str:
    lines = [
        "# Generated command identity table",
        "",
        "Generated from `schema/commands.json`. Do not edit this file directly.",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "| ID | Symbol | Service |",
        "| ---: | --- | --- |",
    ]
    for item in data["commands"]:
        lines.append(f"| `0x{item['id']:04X}` | `{item['name']}` | {item['service']} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate stable protocol command identities")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = load_schema()
    rendered = {"c": render_c(data), "cs": render_cs(data), "md": render_md(data)}
    outputs = {path: rendered[kind] for path, kind in OUTPUTS.items()}
    if args.write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print("generated", path.relative_to(ROOT))
        return 0
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"stale generated file: {path.relative_to(ROOT)}")
    if failures:
        print("COMMAND_SCHEMA_GENERATION_FAIL")
        for failure in failures:
            print(" -", failure)
        return 2
    print(f"COMMAND_SCHEMA_GENERATION_PASS ({len(outputs)} generated files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
