#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema/parameters.json"
OUTPUTS = {
    ROOT / "generated/parameters/bms_parameter_ids.h": "c",
    ROOT / "generated/parameters/ParameterIds.g.cs": "cs",
    ROOT / "docs/generated/PARAMETER_TABLE.md": "md",
}
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
VALID_TYPES = {"I32", "U32", "BOOL"}
VALID_ACCESS = {"user", "service", "factory", "readonly"}


def load_schema() -> dict:
    data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = data.get("schema_version")
    parameters = data.get("parameters")
    if not isinstance(version, int) or version <= 0 or version > 0xFFFF:
        raise SystemExit("parameter schema_version must be 1..65535")
    if not isinstance(parameters, list):
        raise SystemExit("parameter schema parameters must be a list")

    seen_ids: set[int] = set()
    seen_names: set[str] = set()
    for item in parameters:
        if not isinstance(item, dict):
            raise SystemExit("parameter entry must be an object")
        ident = item.get("id")
        name = item.get("name")
        kind = item.get("type")
        unit = item.get("unit")
        access = item.get("write_access")
        persistent = item.get("persistent")
        if not isinstance(ident, int) or ident <= 0 or ident > 0xFFFF:
            raise SystemExit(f"invalid parameter id: {ident!r}")
        if ident in seen_ids:
            raise SystemExit(f"duplicate parameter id: {ident}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            raise SystemExit(f"invalid parameter name: {name!r}")
        if name in seen_names:
            raise SystemExit(f"duplicate parameter name: {name}")
        if kind not in VALID_TYPES:
            raise SystemExit(f"invalid type for {name}: {kind!r}")
        if not isinstance(unit, str) or not unit:
            raise SystemExit(f"invalid unit for {name}")
        if access not in VALID_ACCESS:
            raise SystemExit(f"invalid write_access for {name}: {access!r}")
        if not isinstance(persistent, bool):
            raise SystemExit(f"persistent must be boolean for {name}")
        seen_ids.add(ident)
        seen_names.add(name)

    data["parameters"] = sorted(parameters, key=lambda item: item["id"])
    return data


def render_c(data: dict) -> str:
    lines = [
        "/* Generated from schema/parameters.json. Do not edit. */",
        "#ifndef BMS_PARAMETER_IDS_H",
        "#define BMS_PARAMETER_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define BMS_PARAMETER_SCHEMA_VERSION UINT16_C({data['schema_version']})",
    ]
    for item in data["parameters"]:
        lines.append(f"#define BMS_PARAM_ID_{item['name']} UINT16_C({item['id']})")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_cs(data: dict) -> str:
    lines = [
        "// Generated from schema/parameters.json. Do not edit.",
        "namespace Bms.Protocol.Generated;",
        "",
        "public static class ParameterIds",
        "{",
        f"    public const ushort SchemaVersion = {data['schema_version']};",
    ]
    for item in data["parameters"]:
        name = "".join(part.title() for part in item["name"].lower().split("_"))
        lines.append(f"    public const ushort {name} = {item['id']};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_md(data: dict) -> str:
    lines = [
        "# Generated parameter identity table",
        "",
        "Generated from `schema/parameters.json`. Do not edit this file directly.",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "| ID | Symbol | Type | Unit | Write access | Persistent |",
        "| ---: | --- | --- | --- | --- | --- |",
    ]
    for item in data["parameters"]:
        persistent = "yes" if item["persistent"] else "no"
        lines.append(
            f"| `0x{item['id']:04X}` | `{item['name']}` | `{item['type']}` | "
            f"{item['unit']} | {item['write_access']} | {persistent} |"
        )
    lines.append("")
    return "\n".join(lines)


def expected_outputs(data: dict) -> dict[Path, str]:
    rendered = {"c": render_c(data), "cs": render_cs(data), "md": render_md(data)}
    return {path: rendered[kind] for path, kind in OUTPUTS.items()}


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print("generated", path.relative_to(ROOT))


def check_outputs(outputs: dict[Path, str]) -> None:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path.relative_to(ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            failures.append(f"stale generated file: {path.relative_to(ROOT)}")
    if failures:
        print("PARAMETER_SCHEMA_GENERATION_FAIL")
        for failure in failures:
            print(" -", failure)
        raise SystemExit(2)
    print(f"PARAMETER_SCHEMA_GENERATION_PASS ({len(outputs)} generated files)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate stable parameter identities for firmware, PC and docs")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    outputs = expected_outputs(load_schema())
    if args.write:
        write_outputs(outputs)
    else:
        check_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
