#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema/protections.json"
OUTPUTS = {
    ROOT / "generated/protections/bms_protection_ids.h": "c",
    ROOT / "generated/protections/ProtectionIds.g.cs": "cs",
    ROOT / "docs/generated/PROTECTION_TABLE.md": "md",
}
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
TOKEN_RE = re.compile(r"^[a-z][a-z0-9_]*$")
VALID_KINDS = {"high", "low", "external"}


def load_schema() -> dict:
    data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = data.get("schema_version")
    protections = data.get("protections")
    if not isinstance(version, int) or version <= 0 or version > 0xFFFF:
        raise SystemExit("protection schema_version must be 1..65535")
    if not isinstance(protections, list):
        raise SystemExit("protection schema protections must be a list")

    seen_ids: set[int] = set()
    seen_names: set[str] = set()
    for item in protections:
        if not isinstance(item, dict):
            raise SystemExit("protection entry must be an object")
        ident = item.get("id")
        name = item.get("name")
        category = item.get("category")
        detector_kind = item.get("detector_kind")
        measurement = item.get("measurement")
        if not isinstance(ident, int) or ident <= 0 or ident > 0xFFFF:
            raise SystemExit(f"invalid protection id: {ident!r}")
        if ident in seen_ids:
            raise SystemExit(f"duplicate protection id: {ident}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            raise SystemExit(f"invalid protection name: {name!r}")
        if name in seen_names:
            raise SystemExit(f"duplicate protection name: {name}")
        if not isinstance(category, str) or TOKEN_RE.fullmatch(category) is None:
            raise SystemExit(f"invalid category for {name}: {category!r}")
        if detector_kind not in VALID_KINDS:
            raise SystemExit(f"invalid detector_kind for {name}: {detector_kind!r}")
        if not isinstance(measurement, str) or TOKEN_RE.fullmatch(measurement) is None:
            raise SystemExit(f"invalid measurement for {name}: {measurement!r}")
        seen_ids.add(ident)
        seen_names.add(name)

    data["protections"] = sorted(protections, key=lambda item: item["id"])
    return data


def render_c(data: dict) -> str:
    lines = [
        "/* Generated from schema/protections.json. Do not edit. */",
        "#ifndef BMS_PROTECTION_IDS_H",
        "#define BMS_PROTECTION_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define BMS_PROTECTION_SCHEMA_VERSION UINT16_C({data['schema_version']})",
    ]
    for item in data["protections"]:
        lines.append(f"#define BMS_PROTECTION_ID_{item['name']} UINT16_C({item['id']})")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_cs(data: dict) -> str:
    lines = [
        "// Generated from schema/protections.json. Do not edit.",
        "namespace Bms.Protocol.Generated;",
        "",
        "public static class ProtectionIds",
        "{",
        f"    public const ushort SchemaVersion = {data['schema_version']};",
    ]
    for item in data["protections"]:
        name = "".join(part.title() for part in item["name"].lower().split("_"))
        lines.append(f"    public const ushort {name} = {item['id']};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_md(data: dict) -> str:
    lines = [
        "# Generated protection identity table",
        "",
        "Generated from `schema/protections.json`. Do not edit this file directly.",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "| ID | Symbol | Category | Detector kind | Measurement semantic |",
        "| ---: | --- | --- | --- | --- |",
    ]
    for item in data["protections"]:
        lines.append(
            f"| `0x{item['id']:04X}` | `{item['name']}` | {item['category']} | "
            f"{item['detector_kind']} | `{item['measurement']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def expected_outputs(data: dict) -> dict[Path, str]:
    rendered = {"c": render_c(data), "cs": render_cs(data), "md": render_md(data)}
    return {path: rendered[kind] for path, kind in OUTPUTS.items()}


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print("generated", path.relative_to(ROOT))


def check_outputs(outputs: dict[Path, str]) -> None:
    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path.relative_to(ROOT)}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            failures.append(f"stale generated file: {path.relative_to(ROOT)}")
    if failures:
        print("PROTECTION_SCHEMA_GENERATION_FAIL")
        for failure in failures:
            print(" -", failure)
        raise SystemExit(2)
    print(f"PROTECTION_SCHEMA_GENERATION_PASS ({len(outputs)} generated files)")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate stable protection identities for firmware, PC and docs")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    outputs = expected_outputs(load_schema())
    if args.write:
        write_outputs(outputs)
    else:
        check_outputs(outputs)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
