#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "schema/events.json"
OUTPUTS = {
    ROOT / "generated/events/bms_event_ids.h": "c",
    ROOT / "generated/events/EventIds.g.cs": "cs",
    ROOT / "docs/generated/EVENT_TABLE.md": "md",
}
NAME_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
TOKEN_RE = re.compile(r"^[a-z][a-z0-9_]*$")
VALID_SOURCES = {"boot", "system", "protection", "parameter", "nvm", "comm", "afe", "iap"}
VALID_SEVERITIES = {"info", "warning", "protection", "fault"}


def load_schema() -> dict:
    data = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    version = data.get("schema_version")
    events = data.get("events")
    if not isinstance(version, int) or version <= 0 or version > 0xFFFF:
        raise SystemExit("event schema_version must be 1..65535")
    if not isinstance(events, list):
        raise SystemExit("event schema events must be a list")

    seen_ids: set[int] = set()
    seen_names: set[str] = set()
    for item in events:
        if not isinstance(item, dict):
            raise SystemExit("event entry must be an object")
        ident = item.get("id")
        name = item.get("name")
        source = item.get("source")
        severity = item.get("severity")
        data0 = item.get("data0")
        data1 = item.get("data1")
        if not isinstance(ident, int) or ident <= 0 or ident > 0xFFFF:
            raise SystemExit(f"invalid event id: {ident!r}")
        if ident in seen_ids:
            raise SystemExit(f"duplicate event id: {ident}")
        if not isinstance(name, str) or NAME_RE.fullmatch(name) is None:
            raise SystemExit(f"invalid event name: {name!r}")
        if name in seen_names:
            raise SystemExit(f"duplicate event name: {name}")
        if source not in VALID_SOURCES:
            raise SystemExit(f"invalid source for {name}: {source!r}")
        if severity not in VALID_SEVERITIES:
            raise SystemExit(f"invalid severity for {name}: {severity!r}")
        if not isinstance(data0, str) or TOKEN_RE.fullmatch(data0) is None:
            raise SystemExit(f"invalid data0 semantic for {name}: {data0!r}")
        if not isinstance(data1, str) or TOKEN_RE.fullmatch(data1) is None:
            raise SystemExit(f"invalid data1 semantic for {name}: {data1!r}")
        seen_ids.add(ident)
        seen_names.add(name)

    data["events"] = sorted(events, key=lambda item: item["id"])
    return data


def render_c(data: dict) -> str:
    lines = [
        "/* Generated from schema/events.json. Do not edit. */",
        "#ifndef BMS_EVENT_IDS_H",
        "#define BMS_EVENT_IDS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define BMS_EVENT_SCHEMA_VERSION UINT16_C({data['schema_version']})",
    ]
    for item in data["events"]:
        lines.append(f"#define BMS_EVENT_ID_{item['name']} UINT16_C({item['id']})")
    lines.extend(["", "#endif", ""])
    return "\n".join(lines)


def render_cs(data: dict) -> str:
    lines = [
        "// Generated from schema/events.json. Do not edit.",
        "namespace Bms.Protocol.Generated;",
        "",
        "public static class EventIds",
        "{",
        f"    public const ushort SchemaVersion = {data['schema_version']};",
    ]
    for item in data["events"]:
        name = "".join(part.title() for part in item["name"].lower().split("_"))
        lines.append(f"    public const ushort {name} = {item['id']};")
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_md(data: dict) -> str:
    lines = [
        "# Generated event identity table",
        "",
        "Generated from `schema/events.json`. Do not edit this file directly.",
        "",
        f"Schema version: `{data['schema_version']}`",
        "",
        "| ID | Symbol | Source | Severity | data0 | data1 |",
        "| ---: | --- | --- | --- | --- | --- |",
    ]
    for item in data["events"]:
        lines.append(
            f"| `0x{item['id']:04X}` | `{item['name']}` | {item['source']} | {item['severity']} | "
            f"`{item['data0']}` | `{item['data1']}` |"
        )
    lines.append("")
    return "\n".join(lines)


def expected_outputs(data: dict) -> dict[Path, str]:
    rendered = {"c": render_c(data), "cs": render_cs(data), "md": render_md(data)}
    return {path: rendered[kind] for path, kind in OUTPUTS.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate stable event identities for firmware, PC and docs")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = expected_outputs(load_schema())
    if args.write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print("generated", path.relative_to(ROOT))
        return 0

    failures: list[str] = []
    for path, expected in outputs.items():
        if not path.is_file():
            failures.append(f"missing generated file: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != expected:
            failures.append(f"stale generated file: {path.relative_to(ROOT)}")
    if failures:
        print("EVENT_SCHEMA_GENERATION_FAIL")
        for failure in failures:
            print(" -", failure)
        return 2
    print(f"EVENT_SCHEMA_GENERATION_PASS ({len(outputs)} generated files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
