find_package(Python3 REQUIRED COMPONENTS Interpreter)
set(BMS_GENERATED_DIR ${CMAKE_BINARY_DIR}/generated/${BMS_TARGET});file(MAKE_DIRECTORY ${BMS_GENERATED_DIR})
execute_process(COMMAND ${Python3_EXECUTABLE} ${CMAKE_SOURCE_DIR}/tools/generate_target.py --target ${BMS_TARGET} --out ${BMS_GENERATED_DIR} RESULT_VARIABLE BMS_TARGET_GEN_RESULT)
if(NOT BMS_TARGET_GEN_RESULT EQUAL 0) message(FATAL_ERROR "target generation failed for ${BMS_TARGET}") endif()

function(bms_apply_core_cpu cpu)
 foreach(t bms_base bms_boot_core bms_app_core) target_compile_options(${t} PRIVATE ${cpu} -ffunction-sections -fdata-sections) endforeach()
endfunction()
function(bms_add_images cpu includes startup linker_boot linker_app)
 function(add_one name kind main_file linker define)
  add_executable(${name} ${startup} ${main_file});set_target_properties(${name} PROPERTIES SUFFIX ".elf")
  target_include_directories(${name} PRIVATE ${includes} ${CMAKE_SOURCE_DIR}/platform/common/include ${CMAKE_SOURCE_DIR}/protocol/include ${CMAKE_SOURCE_DIR}/common/include ${CMAKE_SOURCE_DIR}/bootloader/core/include)
  target_compile_definitions(${name} PRIVATE ${define});target_compile_options(${name} PRIVATE ${cpu} -O2 -ffunction-sections -fdata-sections)
  target_link_options(${name} PRIVATE ${cpu} -T${linker} -Wl,--gc-sections -Wl,-Map=${CMAKE_CURRENT_BINARY_DIR}/${name}.map --specs=nano.specs --specs=nosys.specs)
  if(kind STREQUAL "boot") target_link_libraries(${name} PRIVATE bms_base bms_boot_core bms_platform_mcu) else() target_link_libraries(${name} PRIVATE bms_base bms_app_core bms_platform_mcu) endif()
  add_custom_command(TARGET ${name} POST_BUILD COMMAND ${CMAKE_OBJCOPY} -O ihex $<TARGET_FILE:${name}> ${CMAKE_CURRENT_BINARY_DIR}/${name}.hex COMMAND ${CMAKE_OBJCOPY} -O binary $<TARGET_FILE:${name}> ${CMAKE_CURRENT_BINARY_DIR}/${name}.bin COMMAND ${CMAKE_SIZE} $<TARGET_FILE:${name}>)
 endfunction()
 add_one(bms_bootloader boot ${CMAKE_SOURCE_DIR}/bootloader/target/main.c ${linker_boot} BMS_BOOT_IMAGE)
 add_one(bms_app app ${CMAKE_SOURCE_DIR}/app/target/main.c ${linker_app} BMS_APP_IMAGE)
 file(GENERATE OUTPUT ${BMS_GENERATED_DIR}/keil_boot_sources.txt CONTENT "$<JOIN:$<TARGET_PROPERTY:bms_base,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_boot_core,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_platform_mcu,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_vendor_mcu,SOURCES>,\n>\n${CMAKE_SOURCE_DIR}/bootloader/target/main.c\n")
 file(GENERATE OUTPUT ${BMS_GENERATED_DIR}/keil_app_sources.txt CONTENT "$<JOIN:$<TARGET_PROPERTY:bms_base,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_app_core,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_platform_mcu,SOURCES>,\n>\n$<JOIN:$<TARGET_PROPERTY:bms_vendor_mcu,SOURCES>,\n>\n${CMAKE_SOURCE_DIR}/app/target/main.c\n")
endfunction()

if(BMS_TARGET STREQUAL "stm32f030c8_mock")
 set(V ${CMAKE_SOURCE_DIR}/vendor/st/stm32f0_stdperiph_v1.5.0);if(NOT EXISTS ${V}/CMSIS/stm32f0xx.h) message(FATAL_ERROR "Run python tools/bootstrap_vendor.py --family f0") endif()
 set(CPU -mcpu=cortex-m0 -mthumb);set(INC ${CMAKE_SOURCE_DIR}/platform/stm32f0/include ${BMS_GENERATED_DIR} ${V}/CMSIS ${V}/StdPeriph/inc);bms_apply_core_cpu("${CPU}")
 add_library(bms_vendor_mcu STATIC ${V}/StdPeriph/src/stm32f0xx_flash.c ${V}/StdPeriph/src/stm32f0xx_gpio.c ${V}/StdPeriph/src/stm32f0xx_iwdg.c ${V}/StdPeriph/src/stm32f0xx_misc.c ${V}/StdPeriph/src/stm32f0xx_rcc.c ${V}/StdPeriph/src/stm32f0xx_syscfg.c ${V}/StdPeriph/src/stm32f0xx_usart.c)
 target_include_directories(bms_vendor_mcu PUBLIC ${INC});target_compile_definitions(bms_vendor_mcu PUBLIC STM32F030 USE_STDPERIPH_DRIVER);target_compile_options(bms_vendor_mcu PRIVATE ${CPU} -O2 -ffunction-sections -fdata-sections)
 add_library(bms_platform_mcu STATIC platform/stm32f0/src/system_stm32f030_clean.c platform/stm32f0/src/bms_platform_stm32f0.c);target_include_directories(bms_platform_mcu PUBLIC ${INC} ${CMAKE_SOURCE_DIR}/platform/common/include ${CMAKE_SOURCE_DIR}/bootloader/core/include);target_compile_definitions(bms_platform_mcu PUBLIC STM32F030 USE_STDPERIPH_DRIVER);target_compile_options(bms_platform_mcu PRIVATE ${CPU} -O2 -ffunction-sections -fdata-sections);target_link_libraries(bms_platform_mcu PUBLIC bms_vendor_mcu)
 bms_add_images("${CPU}" "${INC}" ${CMAKE_SOURCE_DIR}/platform/stm32f0/startup/startup_stm32f030_gcc.c ${BMS_GENERATED_DIR}/boot.ld ${BMS_GENERATED_DIR}/app.ld)
elseif(BMS_TARGET STREQUAL "stm32f103c8_mock")
 set(V ${CMAKE_SOURCE_DIR}/vendor/st/stm32f10x_stdperiph_v3.5.0);if(NOT EXISTS ${V}/CMSIS/stm32f10x.h) message(FATAL_ERROR "Run python tools/bootstrap_vendor.py --family f1") endif()
 set(CPU -mcpu=cortex-m3 -mthumb);set(INC ${CMAKE_SOURCE_DIR}/platform/stm32f1/include ${BMS_GENERATED_DIR} ${V}/CMSIS ${V}/StdPeriph/inc);bms_apply_core_cpu("${CPU}")
 add_library(bms_vendor_mcu STATIC ${V}/StdPeriph/src/stm32f10x_flash.c ${V}/StdPeriph/src/stm32f10x_gpio.c ${V}/StdPeriph/src/stm32f10x_iwdg.c ${V}/StdPeriph/src/misc.c ${V}/StdPeriph/src/stm32f10x_rcc.c ${V}/StdPeriph/src/stm32f10x_usart.c)
 target_include_directories(bms_vendor_mcu PUBLIC ${INC});target_compile_definitions(bms_vendor_mcu PUBLIC STM32F10X_MD USE_STDPERIPH_DRIVER);target_compile_options(bms_vendor_mcu PRIVATE ${CPU} -O2 -ffunction-sections -fdata-sections)
 add_library(bms_platform_mcu STATIC platform/stm32f1/src/system_stm32f103_clean.c platform/stm32f1/src/bms_platform_stm32f1.c);target_include_directories(bms_platform_mcu PUBLIC ${INC} ${CMAKE_SOURCE_DIR}/platform/common/include ${CMAKE_SOURCE_DIR}/bootloader/core/include);target_compile_definitions(bms_platform_mcu PUBLIC STM32F10X_MD USE_STDPERIPH_DRIVER);target_compile_options(bms_platform_mcu PRIVATE ${CPU} -O2 -ffunction-sections -fdata-sections);target_link_libraries(bms_platform_mcu PUBLIC bms_vendor_mcu)
 bms_add_images("${CPU}" "${INC}" ${CMAKE_SOURCE_DIR}/platform/stm32f1/startup/startup_stm32f103_gcc.c ${BMS_GENERATED_DIR}/boot.ld ${BMS_GENERATED_DIR}/app.ld)
else()
 message(FATAL_ERROR "Unsupported BMS_TARGET=${BMS_TARGET}")
endif()
